### ISSUE TITLE
Cannot start with latest uPortal 5.3.0 SNAPSHOT

### ISSUE THREAD

**Issue by ChristianMurphy** [Jasig/uPortal-start#228]
**Describe the bug**
Portal init fails on latest uPortal 5.3.0 snapshot

**To Reproduce**
1. `./gradle install` in uPortal at version https://github.com/Jasig/uPortal/commit/fb385906e6ed78f20bb704bdd0b6938269ec500c
2. Set uPortal start to use `5.3.0-SNAPHOT`
3. `./gradle portalInit portalOpen`

**Expected behavior**

Build succeeds.

**Stacktrace**

```
FAIL: profile - defaultTemplateUser_default.profile.xml
--------------------------------------------------------------------------------
org.danann.cernunnos.ManagedException: The Cernunnos Runtime encountered an error:
		Origin Document:  file:/home/christian/Projects/uPortal/uPortal-start/.gradle/tomcat/webapps/uPortal/WEB-INF/classes/org/jasig/portal/io/import-profile_v3-2.crn
		Source:  /sql-transaction/with/subtasks/with/subtasks/sql-transaction/sql-upsert
		Entity Name:  <sql-upsert>
	at org.danann.cernunnos.runtime.RuntimeTaskDecorator.perform(RuntimeTaskDecorator.java:93)
	at org.danann.cernunnos.AbstractContainerTask.performSubtasks(AbstractContainerTask.java:148)
	at org.danann.cernunnos.AbstractContainerTask.performSubtasks(AbstractContainerTask.java:123)
	at org.danann.cernunnos.sql.TransactionTask.access$300(TransactionTask.java:40)
	at org.danann.cernunnos.sql.TransactionTask$PerformSubtasksTransactionCallback.doInTransactionWithoutResult(TransactionTask.java:141)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.danann.cernunnos.sql.TransactionTask.perform(TransactionTask.java:115)
	at org.danann.cernunnos.runtime.RuntimeTaskDecorator.perform(RuntimeTaskDecorator.java:77)
	at org.danann.cernunnos.AbstractContainerTask.performSubtasks(AbstractContainerTask.java:148)
	at org.danann.cernunnos.AbstractContainerTask.performSubtasks(AbstractContainerTask.java:123)
	at org.danann.cernunnos.core.WithTask.perform(WithTask.java:90)
	at org.danann.cernunnos.runtime.RuntimeTaskDecorator.perform(RuntimeTaskDecorator.java:77)
	at org.danann.cernunnos.AbstractContainerTask.performSubtasks(AbstractContainerTask.java:148)
	at org.danann.cernunnos.AbstractContainerTask.performSubtasks(AbstractContainerTask.java:123)
	at org.danann.cernunnos.core.WithTask.perform(WithTask.java:90)
	at org.danann.cernunnos.runtime.RuntimeTaskDecorator.perform(RuntimeTaskDecorator.java:77)
	at org.danann.cernunnos.AbstractContainerTask.performSubtasks(AbstractContainerTask.java:148)
	at org.danann.cernunnos.AbstractContainerTask.performSubtasks(AbstractContainerTask.java:123)
	at org.danann.cernunnos.sql.TransactionTask.access$300(TransactionTask.java:40)
	at org.danann.cernunnos.sql.TransactionTask$PerformSubtasksTransactionCallback.doInTransactionWithoutResult(TransactionTask.java:141)
	at org.springframework.transaction.support.TransactionCallbackWithoutResult.doInTransaction(TransactionCallbackWithoutResult.java:34)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.danann.cernunnos.sql.TransactionTask.perform(TransactionTask.java:115)
	at org.danann.cernunnos.runtime.RuntimeTaskDecorator.perform(RuntimeTaskDecorator.java:77)
	at org.danann.cernunnos.runtime.ScriptRunner$TaskDecorator.perform(ScriptRunner.java:436)
	at org.danann.cernunnos.runtime.ScriptRunner.run(ScriptRunner.java:288)
	at org.danann.cernunnos.runtime.PojoTask.perform(PojoTask.java:202)
	at org.apereo.portal.io.xml.crn.CernunnosDataImporter.importDataElement(CernunnosDataImporter.java:50)
	at org.apereo.portal.io.xml.crn.AbstractDom4jImporter.importData(AbstractDom4jImporter.java:72)
	at org.apereo.portal.io.xml.crn.AbstractDom4jImporter.importData(AbstractDom4jImporter.java:41)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.importOrUpgradeData(JaxbPortalDataHandlerService.java:787)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.importData(JaxbPortalDataHandlerService.java:726)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.importData(JaxbPortalDataHandlerService.java:759)
	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService$1.callWithoutResult(JaxbPortalDataHandlerService.java:618)
	at org.apereo.portal.concurrency.CallableWithoutResult.call(CallableWithoutResult.java:24)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [
                            INSERT INTO up_user_profile(user_id, profile_id, profile_fname, profile_name, description, layout_id, structure_ss_id, theme_ss_id) 
                            VALUES(?, ?, ?, ?, ?, ?, ?, ?)
                        ]; integrity constraint violation: NOT NULL check constraint; SYS_CT_10705 table: UP_USER_PROFILE column: USER_ID; nested exception is java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10705 table: UP_USER_PROFILE column: USER_ID
	at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:85)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:73)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:82)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:655)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:876)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:937)
	at org.danann.cernunnos.sql.UpsertTask.doInsert(UpsertTask.java:180)
	at org.danann.cernunnos.sql.UpsertTask.perform(UpsertTask.java:149)
	at org.danann.cernunnos.runtime.RuntimeTaskDecorator.perform(RuntimeTaskDecorator.java:77)
	... 39 more
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10705 table: UP_USER_PROFILE column: USER_ID
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:235)
	at com.sun.proxy.$Proxy222.executeUpdate(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.interceptor.AbstractQueryReport$StatementProxy.invoke(AbstractQueryReport.java:235)
	at com.sun.proxy.$Proxy222.executeUpdate(Unknown Source)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:883)
	at org.springframework.jdbc.core.JdbcTemplate$2.doInPreparedStatement(JdbcTemplate.java:876)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:639)
	... 44 more
```

**Platform:**
 - uPortal Version: 5.3.0-SNAPHOT
 - OS: Linux

**Comment by drewwills** [comment]
@ChristianMurphy -- two points...

  - (1) I strongly suspect this issue stems from data that has been removed in a uPortal-start PR that is waiting for a 5.3.x release

  - (2) It's not a bad idea (probably a very good idea) to update uPortal 5.3.x to make it more resilient to data that is no longer supported.

Perhaps I can take a stab at #2 during the week.
